[features]
seeds = false
skip-lint = false
[programs.localnet]
social_identity = "vH8tAkXTvNMY3RUp3o6YyrRVn7Awe1N536i5X8apkiy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/kunal/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
